name: PR-CI

on:
  pull_request:
    branches:
      - testing

jobs:

  ci-build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install ARM tools
      run: make arm_sdk_install

    - name: Set build variables
      run: |
        PR=${GITHUB_REF}
        PR=${PR##refs/pull/}
        PR=${PR%%/merge}
        echo "GIT_VER=PR${PR}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Build HEX files for multiple targets
      run: make unified FC_VER_SUFFIX="${{ env.GIT_VER }}" FLASH_CONFIG_ERASE=yes

    - name: Move HEX
      run: mv obj/*.hex .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rotorflight-master-${{ env.GIT_VER }}
        path: rotorflight*.hex

